#!/usr/bin/env bash
# =============================================================================
# V-Model XT — Traceability Generator
# Generates a traceability matrix from requirements to tests.
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Guard: refuse if project not initialized
source "${SCRIPT_DIR}/guard-init.sh"
OUTPUT_FILE="${PROJECT_ROOT}/project/10_Documentation/TraceabilityMatrix.md"
TIMESTAMP=$(date +%Y-%m-%d)

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║            V-Model XT — Traceability Generator               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# --- Scan for requirement IDs in markdown files ---
echo "Scanning for requirements..."
REQ_IDS=$(grep -rh 'REQ-[A-Z]*-[0-9]*' "${PROJECT_ROOT}/project/01_Requirements/" 2>/dev/null | grep -oP 'REQ-[A-Z]+-\d+' | sort -u || true)

# --- Scan for test case IDs ---
echo "Scanning for test cases..."
TEST_IDS=$(grep -rh 'TC-[A-Z]*-[0-9]*' "${PROJECT_ROOT}/project/06_Verification/" "${PROJECT_ROOT}/src/" 2>/dev/null | grep -oP 'TC-[A-Z]+-\d+' | sort -u || true)

# --- Scan for risk IDs ---
echo "Scanning for risk items..."
RISK_IDS=$(grep -rh 'FMEA-[0-9]*' "${PROJECT_ROOT}/project/08_RiskManagement/" 2>/dev/null | grep -oP 'FMEA-\d+' | sort -u || true)

REQ_COUNT=$(echo "${REQ_IDS}" | grep -c . || echo "0")
TEST_COUNT=$(echo "${TEST_IDS}" | grep -c . || echo "0")
RISK_COUNT=$(echo "${RISK_IDS}" | grep -c . || echo "0")

echo "  Found ${REQ_COUNT} requirement IDs"
echo "  Found ${TEST_COUNT} test case IDs"
echo "  Found ${RISK_COUNT} risk IDs"
echo ""

# --- Generate traceability report ---
cat > "${OUTPUT_FILE}" << EOF
# Traceability Matrix

**Generated:** ${TIMESTAMP}  
**Project:** $(jq -r '.project.name // "Unknown"' "${PROJECT_ROOT}/dashboard/data/project.json" 2>/dev/null || echo "Unconfigured")

## Summary

| Metric | Count |
|--------|-------|
| Total Requirements | ${REQ_COUNT} |
| Total Test Cases | ${TEST_COUNT} |
| Total Risk Items (FMEA) | ${RISK_COUNT} |
| Requirements with Test Coverage | TBD (analyze manually) |
| Uncovered Requirements | TBD |
| Verified Risk Controls | TBD |

## Requirement-to-Test Traceability

| REQ-ID | Description | Test ID | Status |
|--------|-------------|---------|--------|
EOF

# Add rows (placeholder — in practice, this would parse structured data)
if [[ "${REQ_COUNT}" -gt 0 ]]; then
    while IFS= read -r req_id; do
        echo "| ${req_id} | (extract from source) | (link test) | Pending |" >> "${OUTPUT_FILE}"
    done <<< "${REQ_IDS}"
else
    echo "| — | No requirements found | — | — |" >> "${OUTPUT_FILE}"
fi

cat >> "${OUTPUT_FILE}" << EOF

## Risk-to-Requirement-to-Test Traceability

| FMEA-ID | Risk Control | REQ-ID | Test ID | Verification Status |
|---------|-------------|--------|---------|---------------------|
EOF

if [[ "${RISK_COUNT}" -gt 0 ]]; then
    while IFS= read -r risk_id; do
        echo "| ${risk_id} | (document in FMEA) | (link req) | (link test) | Pending |" >> "${OUTPUT_FILE}"
    done <<< "${RISK_IDS}"
else
    echo "| — | No risk items found | — | — | — |" >> "${OUTPUT_FILE}"
fi

cat >> "${OUTPUT_FILE}" << EOF

## Gaps

Items below lack full traceability:

| Artifact | Gap Type | Recommended Action |
|----------|----------|-------------------|
EOF

# Check for gaps
if [[ "${REQ_COUNT}" -gt 0 && "${TEST_COUNT}" -eq 0 ]]; then
    echo "| All Requirements | Missing tests | Create test cases for all requirements |" >> "${OUTPUT_FILE}"
fi

if [[ "${RISK_COUNT}" -gt 0 && "${REQ_COUNT}" -eq 0 ]]; then
    echo "| All Risk Items | Missing reqs | Link risks to requirements |" >> "${OUTPUT_FILE}"
fi

if [[ "${REQ_COUNT}" -eq 0 && "${TEST_COUNT}" -eq 0 && "${RISK_COUNT}" -eq 0 ]]; then
    echo "| Project | No traceable items | Start documenting requirements, tests, and risks |" >> "${OUTPUT_FILE}"
fi

echo "" >> "${OUTPUT_FILE}"
echo "---" >> "${OUTPUT_FILE}"
echo "*Auto-generated by traceability script. Update manually with detailed trace links.*" >> "${OUTPUT_FILE}"

echo "✅ Traceability matrix written to: ${OUTPUT_FILE}"
echo ""
